### ISSUE TITLE
Log in password issue

### ISSUE THREAD

**Issue by Ikage777** [citizenparker/swsheets#253] opened 2020-04-22 15:03 UTC
I have found a bug with the log in. It does not accept my Password unless I reset it but once I log out and try to log in again it will deny the new password. My account information remains since the character sheet I made is still there so I currently assume it is a password issue only but I could be wrong.

**Comment by duffn** [comment] 2020-04-24 12:43
Thanks for the report. I'll take a look and see if I can reproduce the issue.

**Comment by duffn** [comment] 2024-06-19 15:12
I can't reproduce this, so closing.

**Closed as completed by duffn** 2024-06-19 15:12 UTC
Labels: bug
