### ISSUE TITLE
Server internal error - 500 when saving sheet

### ISSUE THREAD

**Issue by yesmarstar** [citizenparker/swsheets#66] opened 2016-08-30 02:53 UTC
I am trying to add a description to my first force power, but when I save, it usually gives me the included result, and my work is lost. 

![image](https://cloud.githubusercontent.com/assets/21326191/18074528/43b2f032-6e3b-11e6-84a5-38c93135fd84.png)

It doesn't always happen; maybe one in every five saves goes through completely successfully, and my work is saved. I thought the culprit might be particular letters or characters, but it doesn't seem to have any different result no matter what the words are. Other boxes seem to function correctly.

**Comment by sparkertime** [comment] 2016-08-30 19:12
Yikes! Thanks for the report, I confirmed those errors in the logs.

It looks the root cause was actually that the descriptions on those force power/upgrades caused server errors when they were too long. I patched that this morning and I believe your problem should be fixed as of 7A Central Time today.

@yesmarstar Could you let me know if you see the problem again? Otherwise I'll close this as fixed later this week.

**Closed as completed** 2016-09-17 20:40 UTC
